#!/usr/bin/env python3
"""Golden output comparison tests for the YAML-based build pipeline.

These tests compare generated markdown output against manually-reviewed
golden baseline files. If the golden test fails, either:
  1. The generator has a bug (fix the generator)
  2. An intentional change was made (update golden with --update-golden)

Golden files:
  sop/tests/golden/15-method-library.golden.md
  sop/tests/golden/06_METHODS.golden.md

Update golden files:
  python sop/tools/build_runtime_bundle.py --update-golden
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
TOOLS_DIR = ROOT / "sop" / "tools"


def _generator_available() -> bool:
    """Check if build_methods_from_yaml is implemented."""
    sys.path.insert(0, str(TOOLS_DIR))
    try:
        from build_runtime_bundle import build_methods_from_yaml  # noqa: F401
        return True
    except ImportError:
        return False


@pytest.mark.skipif(
    not _generator_available(),
    reason="build_methods_from_yaml not yet implemented (Commit 3)",
)
class TestGeneratedMethodLibrary:
    """Compare generated 15-method-library.md against golden baseline."""

    def test_generated_matches_golden(self) -> None:
        sys.path.insert(0, str(TOOLS_DIR))
        from build_runtime_bundle import build_methods_from_yaml

        generated = build_methods_from_yaml()
        golden_path = GOLDEN_DIR / "15-method-library.golden.md"
        assert golden_path.exists(), "Golden file missing — run --update-golden"
        golden = golden_path.read_text(encoding="utf-8")
        assert generated.strip() == golden.strip(), (
            "Generated 15-method-library.md does not match golden baseline. "
            "If this is intentional, run: python sop/tools/build_runtime_bundle.py --update-golden"
        )


@pytest.mark.skipif(
    not _generator_available(),
    reason="build_methods_from_yaml not yet implemented (Commit 3)",
)
class TestRuntimeMethodsBundle:
    """Compare generated 06_METHODS.md against golden baseline."""

    def test_runtime_matches_golden(self) -> None:
        sys.path.insert(0, str(TOOLS_DIR))
        from build_runtime_bundle import build_methods_from_yaml

        # The runtime bundle is generated by the existing build_methods()
        # which reads from the generated 15-method-library.md.
        # For now, just verify the golden file exists and is non-empty.
        golden_path = GOLDEN_DIR / "06_METHODS.golden.md"
        assert golden_path.exists(), "Golden file missing — run --update-golden"
        golden = golden_path.read_text(encoding="utf-8")
        assert len(golden.strip()) > 100, "Golden file is unexpectedly small"


class TestGoldenFilesExist:
    """Verify golden baseline files are present and non-trivial."""

    def test_method_library_golden_exists(self) -> None:
        path = GOLDEN_DIR / "15-method-library.golden.md"
        assert path.exists(), "Missing 15-method-library.golden.md"
        content = path.read_text(encoding="utf-8")
        assert len(content) > 500, "Golden file too small — likely empty or truncated"

    def test_runtime_methods_golden_exists(self) -> None:
        path = GOLDEN_DIR / "06_METHODS.golden.md"
        assert path.exists(), "Missing 06_METHODS.golden.md"
        content = path.read_text(encoding="utf-8")
        assert len(content) > 200, "Golden file too small — likely empty or truncated"

    def test_method_library_golden_has_required_headings(self) -> None:
        """Verify the golden file has the headings required by the generator contract."""
        path = GOLDEN_DIR / "15-method-library.golden.md"
        content = path.read_text(encoding="utf-8")
        required = [
            "## §1 Purpose",
            "## §2 Method Block Schema",
            "## §2.1 Block Catalog",
            "## §4 Template Chains",
            "## §6 Context Dimensions",
        ]
        for heading in required:
            assert heading in content, f"Golden file missing required heading: {heading}"
