import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/use-toast";

const MAX_CLUSTERS = 5;

function generateNote(
  course: string,
  topic: string,
  los: string[],
  sourceExcerpt: string,
  clusterCount: number,
): string {
  const effectiveCount = Math.min(clusterCount, MAX_CLUSTERS);
  const clusters = Array.from({ length: effectiveCount }, (_, i) => {
    const loSlice = los.filter((_, j) => j % effectiveCount === i);
    const loText = loSlice.length > 0
      ? loSlice.map(lo => `  - ${lo}`).join("\n")
      : "  - (assign LOs here)";
    return `### Cluster ${i + 1}: (name this cluster)

**LOs:**
${loText}

**Key Facts (with source anchors):**
- [ ] Fact 1 — (page/slide ref)
- [ ] Fact 2 — (page/slide ref)

**Interpretation:**
(plain-language explanation)

**Application:**
(clinical scenario or exam pattern)`;
  }).join("\n\n");

  // Mermaid diagram skeleton
  const mermaidNodes = Array.from({ length: effectiveCount }, (_, i) =>
    `    C${i + 1}["Cluster ${i + 1}"]`
  ).join("\n");
  const mermaidEdges = Array.from({ length: effectiveCount }, (_, i) =>
    `    Topic --> C${i + 1}`
  ).join("\n");

  // Retrieval prompts
  const retrievalPrompts = Array.from({ length: effectiveCount }, (_, i) =>
    `#### Cluster ${i + 1}\n1. (free-recall question)\n2. (fill-in or label question)`
  ).join("\n\n");

  const sourceSection = sourceExcerpt.trim()
    ? `## Source Excerpt\n\n> ${sourceExcerpt.trim().replace(/\n/g, "\n> ")}\n`
    : `## Source Excerpt\n\n> (paste source material here)\n`;

  return `# ${topic}

**Course:** ${course || "(unspecified)"}
**Date:** ${new Date().toISOString().slice(0, 10)}
**Status:** Draft — UNVERIFIED until source anchors are filled

---

## Learning Objectives

${los.length > 0 ? los.map(lo => `- ${lo}`).join("\n") : "- (add LOs here)"}

---

${sourceSection}

---

## Clusters (${effectiveCount})

${clusters}

---

## Concept Map

\`\`\`mermaid
graph TD
    Topic["${topic}"]
${mermaidNodes}
${mermaidEdges}
\`\`\`

---

## Retrieval Practice

${retrievalPrompts}

### Transfer Question
(apply knowledge from multiple clusters to a new context)

---

## Next Micro-Task

> (<=15 words: what to study next and when)

---

*Generated by Six-Phase Topic Note Builder*
`;
}

export function TopicNoteBuilder() {
  const { toast } = useToast();
  const [course, setCourse] = useState("");
  const [topic, setTopic] = useState("");
  const [losText, setLosText] = useState("");
  const [sourceExcerpt, setSourceExcerpt] = useState("");
  const [clusterCount, setClusterCount] = useState(4);
  const [output, setOutput] = useState("");

  const handleGenerate = () => {
    if (!topic.trim()) {
      toast({ title: "Topic required", variant: "destructive" });
      return;
    }
    const los = losText.split("\n").map(l => l.trim()).filter(Boolean);

    if (los.length > 0 && clusterCount > MAX_CLUSTERS) {
      toast({
        title: "Too many clusters",
        description: `Max ${MAX_CLUSTERS} clusters. Consider splitting into Part 1 / Part 2.`,
        variant: "destructive",
      });
      return;
    }

    const note = generateNote(course, topic.trim(), los, sourceExcerpt, clusterCount);
    setOutput(note);
    toast({ title: "Note generated", description: "Copy to Obsidian when ready." });
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(output);
      toast({ title: "Copied to clipboard" });
    } catch {
      toast({ title: "Copy failed", description: "Select and copy manually.", variant: "destructive" });
    }
  };

  return (
    <Card className="bg-black/40 border-2 border-secondary/50 rounded-none">
      <CardHeader className="p-3 border-b border-secondary/30">
        <CardTitle className="font-arcade text-xs">SIX-PHASE TOPIC NOTE BUILDER</CardTitle>
        <p className="font-terminal text-[10px] text-muted-foreground mt-1">
          Generate an Obsidian-ready topic note following the Six-Phase SOP. No LLM required — template only.
        </p>
      </CardHeader>
      <CardContent className="p-4 space-y-4">
        {/* Inputs */}
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="font-terminal text-[10px] text-muted-foreground block mb-1">Course</label>
            <input
              value={course}
              onChange={e => setCourse(e.target.value)}
              placeholder="e.g., Anatomy"
              className="w-full bg-black border border-secondary/50 rounded-none px-2 py-1.5 font-terminal text-xs text-white placeholder:text-muted-foreground focus:border-primary outline-none"
            />
          </div>
          <div>
            <label className="font-terminal text-[10px] text-muted-foreground block mb-1">Topic Title *</label>
            <input
              value={topic}
              onChange={e => setTopic(e.target.value)}
              placeholder="e.g., Brachial Plexus"
              className="w-full bg-black border border-secondary/50 rounded-none px-2 py-1.5 font-terminal text-xs text-white placeholder:text-muted-foreground focus:border-primary outline-none"
            />
          </div>
        </div>

        <div>
          <label className="font-terminal text-[10px] text-muted-foreground block mb-1">
            Learning Objectives (1 per line)
          </label>
          <textarea
            value={losText}
            onChange={e => setLosText(e.target.value)}
            placeholder={"Identify the roots of the brachial plexus\nDescribe the trunks and divisions\nList terminal branches"}
            rows={4}
            className="w-full bg-black border border-secondary/50 rounded-none px-2 py-1.5 font-terminal text-xs text-white placeholder:text-muted-foreground focus:border-primary outline-none resize-y"
          />
        </div>

        <div>
          <label className="font-terminal text-[10px] text-muted-foreground block mb-1">
            Source Excerpt (optional — paste key content)
          </label>
          <textarea
            value={sourceExcerpt}
            onChange={e => setSourceExcerpt(e.target.value)}
            placeholder="Paste relevant source material here..."
            rows={3}
            className="w-full bg-black border border-secondary/50 rounded-none px-2 py-1.5 font-terminal text-xs text-white placeholder:text-muted-foreground focus:border-primary outline-none resize-y"
          />
        </div>

        <div className="flex items-center gap-3">
          <label className="font-terminal text-[10px] text-muted-foreground">Clusters (3-5):</label>
          <input
            type="number"
            min={3}
            max={MAX_CLUSTERS}
            value={clusterCount}
            onChange={e => setClusterCount(Math.min(MAX_CLUSTERS, Math.max(3, parseInt(e.target.value) || 3)))}
            className="w-16 bg-black border border-secondary/50 rounded-none px-2 py-1 font-terminal text-xs text-white text-center focus:border-primary outline-none"
          />
          <button
            onClick={handleGenerate}
            className="px-4 py-1.5 bg-primary text-black font-arcade text-xs rounded-none hover:bg-primary/80"
          >
            GENERATE NOTE
          </button>
        </div>

        {/* Output */}
        {output && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-arcade text-[10px] text-primary">OUTPUT</span>
              <button
                onClick={handleCopy}
                className="px-3 py-1 border border-primary/50 text-xs font-arcade text-primary hover:bg-primary/10 rounded-none"
              >
                COPY TO CLIPBOARD
              </button>
            </div>
            <pre className="bg-black border border-secondary/30 p-3 font-terminal text-[10px] text-white overflow-auto max-h-96 whitespace-pre-wrap">
              {output}
            </pre>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
